### ISSUE TITLE
Support for subfolder domains

### ISSUE THREAD

**Issue by How-Bout-No** [oonqt/MBCord#11]
**Describe the feature/change you'd like**
The ability to add servers which are a subfolder of a domain, e.x. https://mydomain.com/jellyfin

**Additional context**
MBCord only allows specifying of a domain and port, which works with subdomains just fine, but with subfolders there's no discernible way to set it up.

**Comment by oonqt** [comment]
In the server address field, have you tried putting in the address with the subfolder? I haven't tried it myself, but it should work fine.

**Comment by Zusier** [comment]
having the same issue, most likely that would work but only with port 80

**Comment by ayyu** [comment]
My Jellyfin server runs using a Caddy reverse proxy and subpath /jellyfin. Tried this while putting address and subpath, for all combinations of port 80/443/8096 and protocol. Always get the error "Invalid server address or login credentials"

**Comment by oonqt** [comment]
I believe the reason for this is because the complete address is formatted like the following:

{protocol_dropdown}://{server_address_field}:{port_field}

With it being formatted like this, putting in an address with a subdomain like myjellyfindomain.com/subpath would be formatted like: https://myjellyfindomain.com/subpath:443

I'll either add a separate field or just use some regex to extract the path from the address field, hopefully I'll have some spare time to do this real quick

**Comment by ayyu** [comment]
something like this in getServerAddress?
```javascript
${this.address}.replace(/(.+?)(\/.+)/,`$1:${this.port}$2`)
```

**Comment by oonqt** [comment]
> something like this in getServerAddress?
> 
> ```js
> var url = new URL(this.protocol + this.address);
> url.port = this.port;
> return url.toString();
> ```

Yes, this is a very clean solution, thank you
I'll release a small patch by today hopefully that will fix this issue

**Comment by oonqt** [comment]
Today™ is here (sorry been busy with other things and totally forgot about this)

You can get the new version here which should allow you to add custom paths [here](https://github.com/oonqt/MBCord/releases)

**Comment by How-Bout-No** [comment]
Yep, everything seems to be working fine now. Thank you!
